name: Twistlock
description: Run Twistlock

inputs:
  tl-token:
    description: The API token
    required: true
  tl-console-url:
    description: The console URL (eg https://console.your-company.org:8083)
    required: true
  tl-cli-version:
    description: The version of the twistlock cli
    required: true
    default: v1
  docker-image:
    description: The name of the Docker image.
    required: true

runs:
  using: composite
  steps:
    - name: Download CLI from Twistlock console
      shell: bash
      run: |
        curl \
          --insecure \
          --token "${{ inputs.tl-token }}" \
          --output ./twistcli \
          "${{ inputs.tl-console-url }}/api/${{ inputs.tl-cli-version }}/util/twistcli"
        chmod a+x ./twistcli

    - name: Scan the image using the Twistlock CLI
      shell: bash
      run: |
        ./twistcli images scan \
          --ci \
          --details \
          -address "${{ inputs.tl-console-url }}" \
          -u "${{ inputs.tl-username }}" \
          -p "${{ inputs.tl-password }}" \
          "${{ inputs.docker-image }}"
